//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Rmt.rc
//
#define ID_EFFECT_DEFAULT               10
#define ID_EFFECT_STOP                  12
#define ID_TUNING_RESET                 13
#define ID_EFFECT_RESTORE               14
#define ID_TUNING_TEST                  15
#define ID_EFFECT_TRY                   16
#define IDR_MAIN_WINDOW                 102
#define IDR_RMTTYPE                     103
#define ID_SONG_SET_BOOKMARK            103
#define IDR_TOOLBAR_BLOCK               104
#define ID_SONG_CLEAR_BOOKMARK          104
#define IDR_TOOLBAR_CHANNELS            105
#define IDR_TOOLBAR_PLAY                106
#define IDB_GFX                         107
#define IDI_ICON_EXCLAMATION            108
#define IDD_ABOUT                       109
#define IDD_CHANGEMAXTRACKLEN           110
#define IDD_CHANNELSSELECT              111
#define IDD_EFFECTS                     112
#define IDD_EXPMSX                      113
#define IDD_EXPORT_ASM                  114
#define IDD_EXPORT_RMTPLAYER_ASM        115
#define IDD_EXPORT_SAP_TYPE_R           116
#define IDD_EXPORT_STRIPPED_RMT         117
#define IDD_FILE_NEW                    120
#define IDD_FILE_PROPRTIES              121
#define IDD_IMPORTMOD                   122
#define IDD_IMPORTMODFINISHED           123
#define IDD_IMPORTTMC                   124
#define IDD_IMPORTTMCFINISHED           125
#define IDD_INSTRCHANGE                 126
#define IDD_INSTRUMENTSELECT            127
#define IDD_OCTAVESELECT                128
#define IDD_OPTIONS                     129
#define IDD_OPTIONS_FILE_PATHS          131
#define IDD_RENUMBERINSTRUMENTS         132
#define IDD_RENUMBERTRACKS              133
#define IDD_SONGINSERTCOPYORCLONEOFSONGLINES 134
#define IDD_SONGTRACKSORDER             135
#define IDD_TRACKSLOAD                  136
#define IDD_TUNING                      137
#define IDD_VOLUMESELECT                138
#define IDS_RMT_AUTHOR                  202
#define IDS_RMT_REPOSITORY              203
#define IDS_RMT_VERSION                 204
#define IDC_ABOUT6502                   1001
#define IDC_ABOUTPOKEY                  1002
#define IDC_ADDR                        1003
#define IDC_AUTHOR                      1004
#define IDC_BASENOTE                    1005
#define IDC_BASETUNING                  1006
#define IDC_BROWSE_INSTRUMENT_FILES_FOLDER 1007
#define IDC_BROWSE_MODULE_FILES_FOLDER  1008
#define IDC_BROWSE_TRACK_FILES_FOLDER   1009
#define IDC_BUTTON1                     1010
#define IDC_BUTTON2                     1011
#define IDC_CHECK1                      1013
#define IDC_CHECK10                     1014
#define IDC_CHECK11                     1015
#define IDC_CHECK12                     1016
#define IDC_CHECK13                     1017
#define IDC_CHECK2                      1018
#define IDC_CHECK3                      1019
#define IDC_CHECK4                      1020
#define IDC_CHECK5                      1021
#define IDC_CHECK6                      1022
#define IDC_CHECK7                      1023
#define IDC_CHECK8                      1024
#define IDC_CHECK9                      1025
#define IDC_CHECKONEINSTRUMENT          1026
#define IDC_CHK_RELOCATE_INSTRUMENTS    1027
#define IDC_CHK_RELOCATE_SONG           1028
#define IDC_CHK_RELOCATE_TRACKS         1029
#define IDC_CLEARALL                    1031
#define IDC_CLONETRACKS                 1032
#define IDC_COLORNUMBER                 1033
#define IDC_COMBO1                      1034
#define IDC_COMBO10                     1035
#define IDC_COMBO11                     1036
#define IDC_COMBO12                     1037
#define IDC_COMBO2                      1038
#define IDC_COMBO3                      1039
#define IDC_COMBO4                      1040
#define IDC_COMBO5                      1041
#define IDC_COMBO6                      1042
#define IDC_COMBO7                      1043
#define IDC_COMBO8                      1044
#define IDC_COMBO9                      1045
#define IDC_COMBOTYPE                   1046
#define IDC_COMBO_ASM_FORMAT            1047
#define IDC_COMBO_LINESAFTER            1048
#define IDC_COPYLEFTRIGHT               1049
#define IDC_COPYRIGHTLEFT               1050
#define IDC_COPYTOCLIPBOARD             1051
#define IDC_CURSOR_CHANNEL_ON_OFF       1054
#define IDC_CURSOR_DIALOG               1056
#define IDC_CURSOR_ENVELOPE_VOLUME      1057
#define IDC_CURSOR_GOTO                 1058
#define IDC_CURSOR_SET_POSITION         1059
#define IDC_DATE                        1060
#define IDC_DEBUGDISPLAY                1061
#define IDC_DEFAULT                     1062
#define IDC_DISPLAYFLATNOTES            1063
#define IDC_EDIT                        1065
#define IDC_EDIT1                       1066
#define IDC_EDIT2                       1067
#define IDC_EDIT_INSTRUMENTS_LABEL      1068
#define IDC_EDIT_SONG_LINES_LABEL       1069
#define IDC_EDIT_TRACKS_LABEL           1070
#define IDC_EFF_COMBO                   1071
#define IDC_EFF_EDIT1                   1072
#define IDC_EFF_EDIT2                   1073
#define IDC_EFF_EDIT3                   1074
#define IDC_EFF_P1                      1075
#define IDC_EFF_P2                      1076
#define IDC_EFF_P3                      1077
#define IDC_GLOBALVOLUMEFADE            1079
#define IDC_INFO                        1080
#define IDC_INFO2                       1081
#define IDC_INSTRUMENT_FILES_FOLDER     1083
#define IDC_KEYBOARD_ASKWHENCONTROL_S   1084
#define IDC_KEYBOARD_ESCRESETATARISOUND 1085
#define IDC_KEYBOARD_LAYOUT             1086
#define IDC_KEYBOARD_REMEMBEROCTAVESANDVOLUMES 1087
#define IDC_KEYBOARD_UPDOWNCONTINUE     1088
#define IDC_L1                          1089
#define IDC_L1D                         1090
#define IDC_L2                          1091
#define IDC_L2D                         1092
#define IDC_L3                          1093
#define IDC_L3D                         1094
#define IDC_L4                          1095
#define IDC_L4D                         1096
#define IDC_LABELSPREFIX                1097
#define IDC_LIST1                       1098
#define IDC_MAJOR_2ND_L                 1099
#define IDC_MAJOR_2ND_R                 1100
#define IDC_MAJOR_3RD_L                 1101
#define IDC_MAJOR_3RD_R                 1102
#define IDC_MAJOR_6TH_L                 1103
#define IDC_MAJOR_6TH_R                 1104
#define IDC_MAJOR_7TH_L                 1105
#define IDC_MAJOR_7TH_R                 1106
#define IDC_MAXTRACKLEN                 1107
#define IDC_MIDI_DEVICE                 1108
#define IDC_MIDI_NOTEOFF                1109
#define IDC_MIDI_TR                     1110
#define IDC_MIDI_VOLUMEOFFSET           1111
#define IDC_MINOR_2ND_L                 1112
#define IDC_MINOR_2ND_R                 1113
#define IDC_MINOR_3RD_L                 1114
#define IDC_MINOR_3RD_R                 1115
#define IDC_MINOR_6TH_L                 1116
#define IDC_MINOR_6TH_R                 1117
#define IDC_MINOR_7TH_L                 1118
#define IDC_MINOR_7TH_R                 1119
#define IDC_MODULE_FILES_FOLDER         1120
#define IDC_MONOSTEREO                  1121
#define IDC_MSXREGIONAUTO               1122
#define IDC_MSXSHUFFLE                  1123
#define IDC_NAME                        1124
#define IDC_NOHWSOUNDBUFFER             1125
#define IDC_NOSTARTINGSONGLINE          1126
#define IDC_NOTHING                     1127
#define IDC_NTSC                        1128
#define IDC_OCTAVE1                     1129
#define IDC_OCTAVE2                     1130
#define IDC_OCTAVE3                     1131
#define IDC_OCTAVE4                     1132
#define IDC_OCTAVE5                     1133
#define IDC_OCTAVE_L                    1134
#define IDC_OCTAVE_R                    1135
#define IDC_OPTIONS_PATHS               1136
#define IDC_OPTIONS_TUNING              1138
#define IDC_PERFECT_4TH_L               1139
#define IDC_PERFECT_4TH_R               1140
#define IDC_PERFECT_5TH_L               1141
#define IDC_PERFECT_5TH_R               1142
#define IDC_PREV                        1143
#define IDC_R1                          1144
#define IDC_R1D                         1145
#define IDC_R2                          1146
#define IDC_R2D                         1147
#define IDC_R3                          1148
#define IDC_R3D                         1149
#define IDC_R4                          1150
#define IDC_R4D                         1151
#define IDC_RADIO1                      1152
#define IDC_RADIO2                      1153
#define IDC_RADIO3                      1154
#define IDC_RADIO4                      1155
#define IDC_RADIO5                      1156
#define IDC_RADIO6                      1157
#define IDC_RADIO7                      1158
#define IDC_RASM_SFX                    1159
#define IDC_RASTERLINE                  1160
#define IDC_RMTFEAT                     1162
#define IDC_RMT_AUTHOR                  1164
#define IDC_RMT_MODULE_ASM_LABEL        1166
#define IDC_RMT_REPOSITORY              1167
#define IDC_RMT_VERSION                 1168
#define IDC_SCALINGPERCENTAGE           1169
#define IDC_SCROLLBAR1                  1170
#define IDC_SFX                         1171
#define IDC_SMOOTH_SCROLL               1172
#define IDC_SONGLINEFROM                1174
#define IDC_SONGLINETO                  1175
#define IDC_SPEEDINFO                   1176
#define IDC_STEREOMONO                  1177
#define IDC_SUBSONGS                    1178
#define IDC_TEMPERAMENT                 1179
#define IDC_TEXT1                       1180
#define IDC_TEXT2                       1181
#define IDC_TITLE                       1182
#define IDC_TITLE2                      1183
#define IDC_TRACKERDRIVERVERSION        1184
#define IDC_TRACKLINEALTNUMBERING       1185
#define IDC_TRACKLINEPRIMARYHIGHLIGHT   1186
#define IDC_TRACKLINESECONDARYHIGHLIGHT 1188
#define IDC_TRACK_FILES_FOLDER          1189
#define IDC_TRITONE_L                   1190
#define IDC_TRITONE_R                   1191
#define IDC_TUNING                      1192
#define IDC_UNISON_L                    1193
#define IDC_UNISON_R                    1194
#define IDC_USEGERMANNOTATION           1195
#define IDC_VOLUMEP                     1196
#define IDC_WARNING                     1197
#define ID_BLOCK_APPLY_EFFECTS          32771
#define ID_BLOCK_COPY                   32772
#define ID_BLOCK_CUT                    32773
#define ID_BLOCK_DECREASE_VOLUME        32774
#define ID_BLOCK_DELETE                 32775
#define ID_BLOCK_EXCHANGE               32776
#define ID_BLOCK_INCREASE_VOLUME        32777
#define ID_BLOCK_PASTE                  32778
#define ID_BLOCK_PASTESPECIAL_MERGEWITHCURRENTCONTENT 32779
#define ID_BLOCK_PASTESPECIAL_SPEEDVALUESONLY 32780
#define ID_BLOCK_PASTESPECIAL_VOLUMEVALUESONLY 32781
#define ID_BLOCK_PLAY_AND_LOOP          32782
#define ID_BLOCK_RESTORE_FROM_BACKUP    32783
#define ID_BLOCK_SELECTALL              32784
#define ID_BLOCK_TOGGLE_MODIFICATION_MODE 32785
#define ID_BLOCK_TRANSPOSE_NOTES_DOWN   32786
#define ID_BLOCK_TRANSPOSE_NOTES_UP     32787
#define ID_BLOCK_USE_NEXT_INSTRUMENT    32788
#define ID_BLOCK_USE_PREVIOUS_INSTRUMENT 32789
#define ID_CHAN1                        32790
#define ID_CHAN2                        32791
#define ID_CHAN3                        32792
#define ID_CHAN4                        32793
#define ID_CHAN5                        32794
#define ID_CHAN6                        32795
#define ID_CHAN7                        32796
#define ID_CHAN8                        32797
#define ID_CHANNELS_CHANNEL1            32798
#define ID_CHANNELS_CHANNEL2            32799
#define ID_CHANNELS_CHANNEL3            32800
#define ID_CHANNELS_CHANNEL4            32801
#define ID_CHANNELS_CHANNEL5            32802
#define ID_CHANNELS_CHANNEL6            32803
#define ID_CHANNELS_CHANNEL7            32804
#define ID_CHANNELS_CHANNEL8            32805
#define ID_CHANNELS_TOGGLE_ACTIVE_CHANNEL_ON_OFF 32809
#define ID_CHANNELS_TOGGLE_ACTIVE_CHANNEL_SOLO 32810
#define ID_CHANNELS_TOGGLE_ALL_CHANNELS_ON_OFF 32811
#define ID_EDIT_ACTIVATE_POKEY_EXPLORER_MODE 32812
#define ID_EDIT_CLEAR_UNDO_REDO_HISTORY 32813
#define ID_EDIT_SWITCH_EDIT_MODE        32817
#define ID_FILE_EXIT                    32819
#define ID_FILE_EXPORT                  32820
#define ID_FILE_IMPORT                  32821
#define ID_FILE_PROPERTIES              32822
#define ID_FILE_REOPEN                  32823
#define ID_HELP_ABOUT                   32824
#define ID_HELP_ABOUT_APP               32825
#define ID_HELP_HELP_TOPICS             32827
#define ID_HELP_ONLINE_HELP             32829
#define ID_INSTRUMENT_CHANGE            32830
#define ID_INSTRUMENT_CLEARALLUNUSEDINSTRUMENTS 32831
#define ID_INSTRUMENT_INFO              32832
#define ID_INSTRUMENT_PASTESPECIAL_ENVELOPEPARAMETERSONLY 32833
#define ID_INSTRUMENT_PASTESPECIAL_INSERTVOLUMEENVSANDENVELOPEPARSTOCURSORPOSITION 32834
#define ID_INSTRUMENT_PASTESPECIAL_TABLEONLY 32835
#define ID_INSTRUMENT_PASTESPECIAL_VOLUMEENVANDENVELOPEPARSONLY 32836
#define ID_INSTRUMENT_PASTESPECIAL_VOLUMELENVELOPEONLY 32837
#define ID_INSTRUMENT_PASTESPECIAL_VOLUMELRENVELOPESONLY 32838
#define ID_INSTRUMENT_PASTESPECIAL_VOLUMELTORENVELOPEONLY 32839
#define ID_INSTRUMENT_PASTESPECIAL_VOLUMERENVELOPEONLY 32840
#define ID_INSTRUMENT_PASTESPECIAL_VOLUMERTOLENVELOPEONLY 32841
#define ID_INSTRUMENT_RENUMBERALLINSTRUMENTS 32842
#define ID_INSTR_ALLINSTRUMENTSCLEANUP  32843
#define ID_INSTR_COPY                   32844
#define ID_INSTR_CUT                    32845
#define ID_INSTR_DELETE                 32846
#define ID_INSTR_LOAD                   32847
#define ID_INSTR_PASTE                  32848
#define ID_INSTR_SAVE                   32849
#define ID_MIDIONOFF                    32850
#define ID_MODULE_TUNING                32851
#define ID_PART_INFO                    32852
#define ID_PART_INSTRUMENTS             32853
#define ID_PART_SONG                    32854
#define ID_PART_TRACKS                  32855
#define ID_SONG_CLEAR_LINE              32858
#define ID_SONG_COPY_LINE               32859
#define ID_SONG_DELETEACTUALLINE        32860
#define ID_SONG_ESCAPE                  32861
#define ID_SONG_EXPANDLOOPSINALLTRACKS  32862
#define ID_SONG_INSERTCOPYORCLONEOFSONGLINES 32863
#define ID_SONG_INSERTNEWEMPTYLINE      32864
#define ID_SONG_INSERTNEWLINEWITHUNUSEDTRACKS 32865
#define ID_SONG_MAKETRACKSDUPLICATE     32866
#define ID_SONG_PASTE_LINE              32867
#define ID_SONG_PLAY_FOLLOW             32869
#define ID_SONG_PLAY_FROM_BOOKMARK      32870
#define ID_SONG_PLAY_FROM_CURRENT_POSITION 32871
#define ID_SONG_PLAY_FROM_CURRENT_POSITION_AND_LOOP 32872
#define ID_SONG_PLAY_FROM_START         32873
#define ID_SONG_PUTNEWEMPTYUNUSEDTRACK  32875
#define ID_SONG_SEARCHANDBUILDLOOPSINALLTRACKS 32876
#define ID_SONG_SIZEOPTIMIZATION        32877
#define ID_SONG_SONGCHANGEMAXIMALLENGTHOFTRACKS 32878
#define ID_SONG_SONG_TOGGLE_TRACK_NUMBER 32879
#define ID_SONG_STOP                    32880
#define ID_SONG_TOGGLE_NTSC             32881
#define ID_SONG_TRACKSORDERCHANGE       32882
#define ID_TOOLBAR_SWITCH_EDIT_MODE     32884
#define ID_TOOLS_OPEN_ASAP_FILE         32885
#define ID_TOOLS_OPEN_ASMA              32886
#define ID_TOOLS_OPTIONS                32887
#define ID_TRACK_ALLTRACKSCLEANUP       32888
#define ID_TRACK_CLEARALLDUPLICATEDTRACKS 32889
#define ID_TRACK_CLEARALLTRACKSUNUSEDINSONG 32890
#define ID_TRACK_COPY                   32891
#define ID_TRACK_CURSORGOTOTHESPEEDCOLUMN 32892
#define ID_TRACK_CUT                    32893
#define ID_TRACK_DELETE                 32894
#define ID_TRACK_EXPANDLOOP             32895
#define ID_TRACK_INFOABOUTUSINGOFACTUALTRACK 32896
#define ID_TRACK_LOAD                   32897
#define ID_TRACK_PASTE                  32898
#define ID_TRACK_RENUMBERALLTRACKS      32899
#define ID_TRACK_SAVE                   32900
#define ID_TRACK_SEARCHANDBUILDLOOP     32901
#define ID_TRACK_SKIP_LINES_AFTER_NOTE_COMBOBOX 32902
#define ID_VIEW_BLOCKTOOLBAR            32903
#define ID_VIEW_INSTRUMENTACTIVEHELP    32904
#define ID_VIEW_PLAYTIMECOUNTER         32905
#define ID_VIEW_POKEYREGS               32906
#define ID_VIEW_VOLUMEANALYZER          32907
#define ID_SONG_INCREASE_PATTERN_STEP_SIZE 32914
#define ID_SONG_DECREASE_PATTERN_STEP_SIZE 32916

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        205
#define _APS_NEXT_COMMAND_VALUE         32920
#define _APS_NEXT_CONTROL_VALUE         1198
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
